/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://ziw5q5atg5e33ow4ka46dwlylq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "Auth": {
        "region": "us-west-2",
        "userPoolId": "us-west-2_QpxhzL1cU",
        "userPoolWebClientId": "5eii0p9lt3aq6idaeo2o5a32ki",
        "identityPoolId": "us-west-2:d14e5f75-6b8b-4844-a4d8-d5f8a9d7752f"
    },
    "Storage": {
        "AWSS3": {
            "bucket": "filestoragestack-s3bucket64cb25af-qwzwdl7rzd0m",
            "region": "us-west-2"
        }
    }
};


export default awsmobile;
